ossim/mat/urls.py
from django.conf.urls import url
from mat import views

app_name = 'mat'

urlpatterns = [
    url(r'^$',views.home_page, name="home"),
    url(r'^mft/$', views.mat_mft_get_data, name="mat-get-data"),
    url(r'^mvt/$', views.mat_mvt_get_data, name="mvt-get-data"),
]

ossim/ossim/urls.py
from django.contrib import admin
#from django.urls import path
from django.conf.urls import include,url
from . import views

app_name='ossim'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/',include('home.urls')),
    url(r'^',include('booting.urls')),
    url(r'^sockets/',include('sockets.urls')),
    url(r'^synchro/',include('synchro.urls')),
    url(r'^file_allocation/',include('file_alloc.urls')),
    url(r'^deadlock/',include('deadlock.urls')),
    url(r'^page/',include('page.urls')),
    url(r'^matdemo/', include('mat.urls')),
    url(r'^team/', views.matindex),
    url(r'^wiki/', views.wiki),
    url(r'^pr/', views.pr),
    url(r'^ds/', views.ds),
    url(r'^ba/', views.ba),
    url(r'^fa/', views.fa),
    url(r'^mvt/', views.mvt),
    url(r'^mft/', views.mft),
    url(r'^ps/', views.ps),
    url(r'^soc/', views.soc),
    url(r'^sync/', views.sync),
    url(r'^disk/',include('disk_sched.urls'),name='disk'),
    url(r'^process/',include('process.urls'))
]

ossim/mat/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

ossim/mat/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
import json

def home_page(request):
    return render(request, 'mat/index.html')

def mat_mft_get_data(request):
    variables = ['total_memory', 'no_of_blocks']
    submitted = True
    context = {}
    block_size = [0,1,2,3,4,5,6,7,8,0,1,1,1,1,1]
    context['invalid_data'] = False
    for x in variables:
        submitted = request.POST.get(x,False)
        if submitted is False:
            print("Hello")
            break
        else:
            try:
                context[x] = int(request.POST.get(x))
            except ValueError:
                context['invalid_data'] = True
                break

    if context['invalid_data'] is False and submitted:
        for i in range(1, context['no_of_blocks']+1):
            block_size[i] = request.POST.get('block_size_' + str(i))
        context['block_size'] = json.dumps(block_size)

    if submitted is False or context['invalid_data'] is True:
        return render(request, 'mat/mft/get_data.html', context)
    else:
        return render(request, 'mat/mft/show_demo.html', context)

def mat_mvt_get_data(request):
    if request.POST:
        context = {
            'totalMemory' : request.POST['total_memory'],
            'inputMemory' : request.POST['input_memory']
        }
        return render(request, 'mat/mvt/show_demo.html', context)
    return render(request, 'mat/mvt/get_data.html')

ossim/templates/mat/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>
        Memory Allocation Techniques
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body  style="background-image: url('http://sfwallpaper.com/images/background-image-for-website-9.jpg');background-size:cover">
<div class="container" style="background-color: black;opacity: 0.8;margin-top:100px;" >
    <div id="top-content" style="padding-top: 25px">
        <h1 id="page-heading" align="center">
           <img src="https://www.technicalfan.com/wp-content/uploads/2018/10/Memory.jpg" alt="MemoryManagement" width="460" height="350">
        </h1>
    </div>
    <div id="middle-content" style="margin-top:40px;padding-bottom:40px" align="center">
        <br>
        <div class="row">
            
            <div class="col-sm-4" align="center" style="height:200px; margin-left:380px;margin-top:10px;background-color: red">
                <a href="{% url 'mat:mat-get-data' %}" >
                <div style="padding-top: 50px">
                    <b style="color: black;font-size:50px;">
                        <p style = "font-family:courier;font-size:16px;font-style:bold;">MFT</b>
                </div>
                </a>
            </div>
            <div class="col-sm-4" align="center"  style="height:200px; margin-left:380px;margin-top:10px;background-color:red;float: right">
                <a href="{% url 'mat:mvt-get-data' %}">
                <div style="padding-top: 50px">
                    <b style="color: black;font-size:50px;">
                        <p style = "font-family:courier;font-size:16px;font-style:bold;">MVT</b>
                </div>
                </a>
            </div>
        </div>
    </div>
</div>
</body>
<br>
	<div class="container-fluid" style="padding:0px 20px 20px 0px;margin-bottom: 40px">
		<a href="/login/desktop">
			<button type="button" class="btn btn-primary"  style="float:right">Return to Desktop</button>
		</a>
	</div>
</html>

ossim/templates/mat/teamindex.html
<!DOCTYPE html>

<style>

/* Three columns side by side */

body{
  background-color: #AF7AC5;
}

.column {
  float: left;
  width: 17.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

/* Display the columns below each other instead of side by side on small screens */
@media screen and (max-width: 500px) {
  .column {
    width: 100%;
    display: block;
  }
}

/* Add some shadows to create a card effect */
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  background-color: #5DADE2;
}

/* Some left and right padding inside the container */
.container {
  padding: 0 16px;
}

/* Clear floats */
.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}
</style>

<head>
  <link href="css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
  <div class="row">
  <div class="column">
    <div class="card">
      <!-- <img src="img1.jpg" alt="Jane" style="width:100%"> -->
      <div class="container">
        <h2>R Kaushikq</h2>
        <p>Contributor</p>  
        
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
<!--       <img src="img2.jpg" alt="Mike" style="width:100%">
 -->      <div class="container">
        <h2>Rahul Gite</h2>
        <p>Contributor</p>
        
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
     <!--  <img src="img3.jpg" alt="John" style="width:100%"> -->
      <div class="container">
        <h2>Ranjana</h2>
        <p>Contributor</p>
      </div>
    </div>
  </div>
<div class="column">
    <div class="card">
      <!-- <img src="img3.jpg" alt="John" style="width:100%"> -->
      <div class="container">
        <h2>Rahul</h2>
        <p>Contributor</p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card">
      <!-- <img src="img3.jpg" alt="John" style="width:100%"> -->
      <div class="container">
        <h2>Rishi</h2>
        <p>Contributor</p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <!-- <img src="img3.jpg" alt="John" style="width:100%"> -->
      <div class="container">
        <h2>Rohit</h2>
        <p>Contributor</p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card">
      <!-- <img src="img3.jpg" alt="John" style="width:100%"> -->
      <div class="container">
        <h2>Rujuta</h2>
        <p>Contributor</p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card">
      <!-- <img src="img3.jpg" alt="John" style="width:100%"> -->
      <div class="container">
        <h2>Sachin</h2>
        <p>Contributor</p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card">
      <!-- <img src="img3.jpg" alt="John" style="width:100%"> -->
      <div class="container">
        <h2>Sanjana</h2>
        <p>Contributor</p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card">
      <!-- <img src="img3.jpg" alt="John" style="width:100%"> -->
      <div class="container">
        <h2>Saurabh</h2>
        <p>Contributor</p>
      </div>
    </div>
  </div>
  
</div>
</body>

ossim/templates/mat/wiki.html
<!DOCTYPE html>
<html>
<title>WIKI PAGES</title>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style type="text/css">
  .btn-group button {
  background-color: #4CAF50; /* Green background */
  border: 1px solid green; /* Green border */
  color: white; /* White text */
  padding: 25px 24px; /* Some padding */
  cursor: pointer; /* Pointer/hand icon */
  width: 100%; /* Set a width if needed */
  display: block; /* Make the buttons appear below each other */
  font-weight: bold;
  font-size: 30px
}

.btn-group button:not(:last-child) {
  border-bottom: none; /* Prevent double borders */
}

/* Add a background color on hover */
.btn-group button:hover {
  background-color: #3e8e41;
}
</style>
<body>
  <div class="btn-group">
  <button onclick="location.href='../pr'">PAGE REPLACEMENT</button>
  <button onclick="location.href='../ds'">DISK SCHEDULING</button>
  <button onclick="location.href='../ba'">BANKERS ALGORITHM</button>
  <button onclick="location.href='../fa'">FILE ALLOCATION</button>
  <button onclick="location.href='../mvt'">MVT</button>
  <button onclick="location.href='../mft'">MFT</button>
  <button onclick="location.href='../ps'">PROCESS SCHEDULING</button>
  <button onclick="location.href='../soc'">SOCKETS</button>
  <button onclick="location.href='../sync'">SYNCHRONIZATION</button>
  
</div>
<footer class="w3-center w3-light-grey w3-padding-32">
  <p><a href= "../team" title="W3.CSS" style="padding : 15px" class="w3-hover-text-green">TEAM</a>
      <a href= "../login/desktop" title="W3.CSS" style="padding : 15px" class="w3-hover-text-green">HOME</a>
  </p>
  <p></p>
</footer>
</body>

</html>

ossim/templates/mat/wikiba.html
<!DOCTYPE html>
<html>
{%load static%}
    <title>Banker's Algorithm Wiki</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <style>
        body {font-family: "Times New Roman", Georgia, Serif;}
        h1,h2,h3,h4,h5,h6 {
            font-family: "Playfair Display";
            letter-spacing: 5px;
        }
    </style>

<body>

<!-- Navbar (sit on top) -->
    <div class="w3-top">
        <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
            <a href="#home" class="w3-bar-item w3-button">Banker's Algorithm Wiki Page</a>
            <!-- Right-sided navbar links. Hide them on small screens -->
            <div class="w3-right w3-hide-small">
                <a href="#about" class="w3-bar-item w3-button">About</a>
                <a href="#menu" class="w3-bar-item w3-button">Algorithms</a>
            </div>
        </div>
    </div>

<!-- Page content -->
    <div class="w3-content" style="max-width:1100px">

  <!-- About Section -->
    <div class="w3-row w3-padding-64" id="about">
        <div class="w3-col m6 w3-padding-large w3-hide-small">
            <img src="{%static '/images/B1.png'%}" class="w3-round w3-image w3-opacity-min" alt="B" width="600" height="750" style = "padding-top: 500px">
        </div>

        <div class="w3-col m6 w3-padding-large">
            <h1 class="w3-center">About Banker's Algorithm</h1><br>
            <p class="w3-large">Banker's algorithm is a deadlock avoidance algorithm. It is named so because this algorithm is used in banking systems to determine whether a loan can be granted or not.<br>
                                Consider there are n account holders in a bank and the sum of the money in all of their accounts is S. Everytime a loan has to be granted by the bank, it subtracts the loan amount from the total money the bank has.
                                Then it checks if that difference is greater than S. It is done because, only then, the bank would have enough money even if all the n account holders draw all their money at once.<br>
                                Banker's algorithm works in a similar way in computers.<br>
                                Whenever a new process is created, it must specify the maximum It is an n x m matrix which represents the number of resources of each type currently allocated to each process. If Allocation[i][j] = k, then process P(i) is currently allocated k instances of resource type R(j).
                                instances of each resource type that it needs, exactly.</p>
            <p class="w3-large w3-text-grey w3-hide-medium">Let us assume that there are n processes and m resource types. Some data structures that are used to implement the banker's algorithm are:
                                                            1.<u>Available</u><br>
                                                            It is an array of length m. It represents the number of available resources of each type. If Available[j] = k, then there are k instances available, of resource type R(j).<br>
                                                            2.<u>Max</u><br>
                                                            It is an n x m matrix which represents the maximum number of instances of each resource that a process can request. If Max[i][j] = k, then the process P(i) can request atmost k instances of resource type R(j).<br>
                                                            3.<u>Allocation</u><br>
                                                            It is an n x m matrix which represents the number of resources of each type currently allocated to each process. If Allocation[i][j] = k, then process P(i) is currently allocated k instances of resource type R(j).
                                                            4.<u>Need</u><br>
                                                            It is an n x m matrix which indicates the remaining resource needs of each process. If Need[i][j] = k, then process P(i) may need k more instances of resource type R(j) to complete its task.</p>
        </div>
    </div>
    <hr>

  <!-- Menu Section -->
    <div class="w3-row w3-padding-64" id="menu">
        <div class="w3-col l6 w3-padding-large">
            <h1 class="w3-center">Algorithms</h1><br>
            <h4>Safety Algorithm</h4>
            <p class="w3-text-grey">1.Let Work and Finish be vectors of length m and n, respectively. Initially, <br>
                                    -------------------------------------<br>
                                    <code>Work = Available<br>
                                    Finish[i] =false for i = 0, 1, ... , n - 1.<br></code>
                                    -------------------------------------<br>
                                    This means, initially, no process has finished and the number of available resources is represented by the Available array.<br>
                                    2.Find an index i such that both<br>
                                    -------------------------------------<br>
                                    <code>Finish[i] ==false<br>
                                    Need(i) <= Work<br></code>
                                    -------------------------------------<br>
                                    If there is no such i present, then proceed to step 4.<br>
                                    It means, we need to find an unfinished process whose need can be satisfied by the available resources. If no such process exists, just go to step 4.<br>
                                    3.Perform the following: <br>
                                    -------------------------------------<br>
                                    <code>Work = Work + Allocation;<br>
                                    Finish[i] = true;<br></code>
                                    -------------------------------------<br>
                                    Go to step 2.<br>
                                    When an unfinished process is found, then the resources are allocated and the process is marked finished. And then, the loop is repeated to check the same for all other processes.<br>
                                    4.If Finish[i] == true for all i, then the system is in a safe state.<br>
                                    That means if all processes are finished, then the system is in safe state.</p>
            <h4>Resource Request Algorithm</h4>
            <p class="w3-text-grey">1.If number of requested instances of each resource is less than the need (which was declared previously by the process), go to step 2.<br>
                                    2.If number of requested instances of each resource type is less than the available resources of each type, go to step 3. If not, the process has to wait because sufficient resources are not available yet.<br>
                                    3.Now, assume that the resources have been allocated. Accordingly do,<br>
                                    -------------------------------------<br>
                                    <code>Available = Available - Request(i)<br>
                                    Allocation(i) = Allocation(i) + Request(i)<br>
                                    Need(i) = Need(i) - Request(i)<br></code>
                                    -------------------------------------</p>
        </div>
        <div class="w3-col l6 w3-padding-large">
            <img src="{%static '/images/B2.png'%}" class="w3-round w3-image w3-opacity-min" alt="B" style="width:100%; padding-top: 450px">
        </div>
    </div>
    <hr>

<!-- End page content -->
    </div>

<!-- Footer -->
<<footer class="w3-center w3-light-grey w3-padding-32">
  <p><a href= "../team" title="W3.CSS" style="padding : 15px" class="w3-hover-text-green">TEAM</a>
      <a href= "../login/desktop" title="W3.CSS" style="padding : 15px" class="w3-hover-text-green">HOME</a>
  </p>
  <p></p>
</footer>

</body>
</html>

ossim/templates/mat/wikidisk.html
<!DOCTYPE html>
<html>
{% load static %}
    <title>Disk Scheduling Wiki</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <style>
        body {font-family: "Times New Roman", Georgia, Serif;}
        h1,h2,h3,h4,h5,h6 {
            font-family: "Playfair Display";
            letter-spacing: 5px;
        }
    </style>

<body>

<!-- Navbar (sit on top) -->
    <div class="w3-top">
        <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
            <a href="#home" class="w3-bar-item w3-button">Disk Scheduling Wiki Page</a>
            <!-- Right-sided navbar links. Hide them on small screens -->
            <div class="w3-right w3-hide-small">
                <a href="#about" class="w3-bar-item w3-button">About</a>
                <a href="#menu" class="w3-bar-item w3-button">Types</a>
            </div>
        </div>
    </div>

<!-- Page content -->
    <div class="w3-content" style="max-width:1100px">

  <!-- About Section -->
    <div class="w3-row w3-padding-64" id="about">
        <div class="w3-col m6 w3-padding-large w3-hide-small">
            <img src="{% static '/images/D1.png' %}" class="w3-round w3-image w3-opacity-min" alt="D" width="600" height="750" style = "padding-top: 50px">
        </div>

        <div class="w3-col m6 w3-padding-large">
            <h1 class="w3-center">About Disk Scheduling</h1><br>
            <p class="w3-large">Disk scheduling is is done by operating systems to schedule I/O requests arriving for disk. Disk scheduling is also known as I/O scheduling.<br>
                                Disk scheduling is important because:<br>
                                1.Multiple I/O requests may arrive by different processes and only one I/O request can be served at a time by disk controller. Thus other I/O requests need to wait in waiting queue and need to be scheduled.<br>
                                2.Two or more request may be far from each other so can result in greater disk arm movement.<br>
                                3.Hard drives are one of the slowest parts of computer system and thus need to be accessed in an efficient manner.<br></p>
    </div>
    <hr>

  <!-- Menu Section -->
    <div class="w3-row w3-padding-64" id="menu">
        <div class="w3-col l6 w3-padding-large">
            <h1 class="w3-center">Types of MFT</h1><br>
            <h4>FCFS</h4>
            <p class="w3-text-grey">FCFS is the simplest of all the Disk Scheduling Algorithms. In FCFS, the requests are addressed in the order they arrive in the disk queue.</p><br>

            <h4>SSTF</h4>
            <p class="w3-text-grey">In SSTF (Shortest Seek Time First), requests having shortest seek time are executed first. So, the seek time of every request is calculated in advance in queue and then they are scheduled according to their calculated seek time.
                                    As a result, the request near the disk arm will get executed first. SSTF is certainly an improvement over FCFS as it decreases the average response time and increases the throughput of system.</p><br>

            <h4>SCAN</h4>
            <p class="w3-text-grey">In SCAN algorithm the disk arm moves into a particular direction and services the requests coming in its path and after reaching the end of disk, it reverses its direction and again services the request arriving in its path.
                                    So, this algorithm works like an elevator and hence also known as elevator algorithm. As a result, the requests at the midrange are serviced more and those arriving behind the disk arm will have to wait.</p><br>
            <h4>CSCAN</h4>
            <p class="w3-text-grey">In SCAN algorithm, the disk arm again scans the path that has been scanned, after reversing its direction. So, it may be possible that too many requests are waiting at the other end or there may be zero or few requests pending at the scanned area.</p><br>
            <h4>LOOK</h4>
            <p class="w3-text-grey">It is similar to the SCAN disk scheduling algorithm except the difference that the disk arm in spite of going to the end of the disk goes only to the last request to be serviced in front of the head and then reverses its direction from there only.
                                    Thus it prevents the extra delay which occurred due to unnecessary traversal to the end of the disk.</p><br>
            <h4>CLOOK</h4>
            <p class="w3-text-grey">As LOOK is similar to SCAN algorithm, in similar way, CLOOK is similar to CSCAN disk scheduling algorithm. In CLOOK, the disk arm inspite of going to the end goes only to the last request to be serviced in front of the head and then from there goes to the other end’s last request.
                                    Thus, it also prevents the extra delay which occurred due to unnecessary traversal to the end of the disk.</p><br>
        </div>
        <div class="w3-col l6 w3-padding-large">
            {% load static %}
            <img src="{% static '/images/D2.jpg' %}" class="w3-round w3-image w3-opacity-min" alt="D" style="width:100%; padding-top: 150px">
            <img src="{% static '/images/D3.jpg' %}" class="w3-round w3-image w3-opacity-min" alt="D" style="width:100%; padding-top: 150px">
        </div>
    </div>
    <hr>

<!-- End page content -->
    </div>

<!-- Footer -->
<footer class="w3-center w3-light-grey w3-padding-32">
  <p><a href= "../team" title="W3.CSS" style="padding : 15px" class="w3-hover-text-green">TEAM</a>
      <a href= "../login/desktop" title="W3.CSS" style="padding : 15px" class="w3-hover-text-green">HOME</a>
        </p>
</footer>

</body>
</html>

ossim/templates/mat/wikimft.html
<!DOCTYPE html>
<html>
{%load static%}
    <title>MFT Wiki</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <style>
        body {font-family: "Times New Roman", Georgia, Serif;}
        h1,h2,h3,h4,h5,h6 {
            font-family: "Playfair Display";
            letter-spacing: 5px;
        }
    </style>

<body>

<!-- Navbar (sit on top) -->
    <div class="w3-top">
        <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
            <a href="#home" class="w3-bar-item w3-button">MFT Wiki Page</a>
            <!-- Right-sided navbar links. Hide them on small screens -->
            <div class="w3-right w3-hide-small">
                <a href="#about" class="w3-bar-item w3-button">About</a>
                <a href="#menu" class="w3-bar-item w3-button">Types</a>
            </div>
        </div>
    </div>

<!-- Page content -->
    <div class="w3-content" style="max-width:1100px">

  <!-- About Section -->
    <div class="w3-row w3-padding-64" id="about">
        <div class="w3-col m6 w3-padding-large w3-hide-small">
            <img src="{%static '/images/MFT1.jpg' %}" class="w3-round w3-image w3-opacity-min" alt="MFT 1" width="600" height="750" style = "padding-top: 50px">
        </div>

        <div class="w3-col m6 w3-padding-large">
            <h1 class="w3-center">About MFT</h1><br>
            <p class="w3-large">MFT (Multiprogramming with a Fixed number of Tasks) is one of the old memory management techniques in which the memory is partitioned into fixed size partitions and each job is assigned to a partition.
                The memory assigned to a partition does not change.</p>
                <p class="w3-large w3-text-grey w3-hide-medium"><b><u>Advantages</u></b>: At the time of compilation only the address of each word can be given. Or we can bind address at the compile time.<br>
                                                        <b><u>Disadvantages</u></b>: Degree of multiprogramming is rigid ,its is not flexible because we cannot  change the no. of blocks. memory wastage is caused due to fragmentation.<br>
                                                        <b><u>Fragmentation</u></b>: <br>1.Internal: Partial or Incomplete usage of a block of memory<br>2.External: Entire block of available memory cannot be used.</p>
        </div>
    </div>
    <hr>

  <!-- Menu Section -->
    <div class="w3-row w3-padding-64" id="menu">
        <div class="w3-col l6 w3-padding-large">
            <h1 class="w3-center">Types of MFT</h1><br>
            <h4>Best Fit</h4>
            <p class="w3-text-grey">The best fit deals with allocating the smallest free partition which meets the requirement of the requesting process. This algorithm first searches the entire list of free partitions and considers the smallest hole that is adequate. It then tries to find a hole which is close to actual process size needed.</p><br>

            <h4>First Fit</h4>
            <p class="w3-text-grey">In the first fit approach is to allocate the first free partition or hole large enough which can accommodate the process. It finishes after finding the first suitable free partition.</p><br>

            <h4>Worst Fit</h4>
            <p class="w3-text-grey">In worst fit approach is to locate largest available free portion so that the portion left will be big enough to be useful. It is the reverse of best fit.</p><br>
        </div>
        <div class="w3-col l6 w3-padding-large">
            <img src="{%static '/images/MFT2.jpg' %}" class="w3-round w3-image w3-opacity-min" alt="MFT2" style="width:100%; padding-top: 50px">
        </div>
    </div>
    <hr>

<!-- End page content -->
    </div>

<!-- Footer -->
<footer class="w3-center w3-light-grey w3-padding-32">
  <p><a href= "../team" title="W3.CSS" style="padding : 15px" class="w3-hover-text-green">TEAM</a>
      <a href= "../login/desktop" title="W3.CSS" style="padding : 15px" class="w3-hover-text-green">HOME</a>
  </p>
  <p></p>
</footer>

</body>
</html>