ossim/home/urls.py
from django.conf.urls import url,include
from django.contrib import admin
#from django.urls import path

from . import views

app_name = 'home'
urlpatterns =[

    url(r'^$',views.main ),
    url(r'^desktop/',views.Desktop ,name='desktop'),

    url(r'^desktop/Task.html/', views.Task,name='task'),
    url(r'^desktop/terminal/',views.Terminal,name = 'terminal')


]

ossim/mat/urls.py
from django.conf.urls import url
from mat import views

app_name = 'mat'

urlpatterns = [
    url(r'^$',views.home_page, name="home"),
    url(r'^mft/$', views.mat_mft_get_data, name="mat-get-data"),
    url(r'^mvt/$', views.mat_mvt_get_data, name="mvt-get-data"),
]

ossim/ossim/urls.py
from django.contrib import admin
#from django.urls import path
from django.conf.urls import include,url
from . import views

app_name='ossim'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/',include('home.urls')),
    url(r'^',include('booting.urls')),
    url(r'^sockets/',include('sockets.urls')),
    url(r'^synchro/',include('synchro.urls')),
    url(r'^file_allocation/',include('file_alloc.urls')),
    url(r'^deadlock/',include('deadlock.urls')),
    url(r'^page/',include('page.urls')),
    url(r'^matdemo/', include('mat.urls')),
    url(r'^team/', views.matindex),
    url(r'^wiki/', views.wiki),
    url(r'^pr/', views.pr),
    url(r'^ds/', views.ds),
    url(r'^ba/', views.ba),
    url(r'^fa/', views.fa),
    url(r'^mvt/', views.mvt),
    url(r'^mft/', views.mft),
    url(r'^ps/', views.ps),
    url(r'^soc/', views.soc),
    url(r'^sync/', views.sync),
    url(r'^disk/',include('disk_sched.urls'),name='disk'),
    url(r'^process/',include('process.urls'))
]

ossim/home/models.py
from django.db import models

# Create your models here.

ossim/home/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
    return render(request,'home/home.html')


def Login(request):
    return render(request,'home/Login.html')

def Desktop(request):
    return render(request,'home/Desktop.html')

def Task(request):
    return render(request,'home/Task.html')

def Terminal(request):
    return render(request,'home/terminal.html')

ossim/home/templates/home/Task.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Task Manager</title>

        {% load staticfiles %}

        <link rel="stylesheet" type="text/css" href="{% static 'home/assets/css/jquery-ui.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'home/assets/css/task.css' %}" />
         <link rel="stylesheet" type="text/css" href="{% static 'home/assets/jquery-ui.min.css' %}" />
              <link rel="stylesheet" type="text/css" href="{% static 'home/assets/css/font-awesome.min.css' %}" />

    </head>
    <body>
        
        <div id="titleBar">
            <span id="titleName" class="title">Task Manager</span>
            <a  href="{% url 'home:desktop' %}"><span id="titleExit" class="title" style="color: white">X</span></a>
        </div>
        
        <!-- Contains play, pause and stop -->
        <div id="topPanel">
                <span id="playControl">
                    <span id="play" class="circle">
                        <i class="fa fa-play"></i>
                    </span>
                    <span id="pause" class="circle">
                        <i class="fa fa-pause"></i>
                    </span>
                    <span id="stop" class="circle">
                        <i class="fa fa-stop"></i>
                    </span>
                </span>
                
<!--                <span class="vSpacer"></span>-->
                
                <span id="speedHolder">
                    Speed: <div  id="speedSlider" class="mySlider"></div>
                </span>
                
<!--                <span class="vSpacer"></span>-->
                
                <span id="quantumHolder">
                    Quantum: <div id="quantumSlider" class="mySlider"></div>
                </span>
        </div>
        <!-- end control div -->

        <div id="mainContainer" class="row">

            <div id="windowWrapper" class="col-xs-10">
                <div id="myMainWindow">
                    <canvas id="canvas0"></canvas>
                    <canvas id="canvas1"></canvas>
                    <canvas id="canvas2"></canvas>
                    <canvas id="canvas3"></canvas>
                </div>  
            </div>
            
            <!-- task managment [add, remove, clear] -->
            <div id="myRightPanel" class="col-xs-2">
                <div id="manageDiv">
                    <ul class="list-group strings">
                        <!--li class="list-group-item">abcdef <a href="#" class="badge">x</a></li-->
                    </ul>
                    <div id="addTaskDiv">
                        <input type="text" id="word" placeholder="Task Text" maxLength="7"/> 
                        <input type="button" id="addTask" value="Add"/>
                    </div>
                </div>
            </div>
            <!-- end task managments -->
            
            <div class="fix"></div>
        </div>


        <script type="text/javascript" src="{% static 'home/assets/js/jquery-3.2.1.js' %}"></script>
        <script type="text/javascript" src="{% static 'home/assets/js/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'home/assets/js/jcanvas.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'home/assets/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'home/assets/js/task2.js' %}"></script>

    </body>
</html>