ossim/mat/urls.py
from django.conf.urls import url
from mat import views

app_name = 'mat'

urlpatterns = [
    url(r'^$',views.home_page, name="home"),
    url(r'^mft/$', views.mat_mft_get_data, name="mat-get-data"),
    url(r'^mvt/$', views.mat_mvt_get_data, name="mvt-get-data"),
]

ossim/ossim/urls.py
from django.contrib import admin
#from django.urls import path
from django.conf.urls import include,url
from . import views

app_name='ossim'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/',include('home.urls')),
    url(r'^',include('booting.urls')),
    url(r'^sockets/',include('sockets.urls')),
    url(r'^synchro/',include('synchro.urls')),
    url(r'^file_allocation/',include('file_alloc.urls')),
    url(r'^deadlock/',include('deadlock.urls')),
    url(r'^page/',include('page.urls')),
    url(r'^matdemo/', include('mat.urls')),
    url(r'^team/', views.matindex),
    url(r'^wiki/', views.wiki),
    url(r'^pr/', views.pr),
    url(r'^ds/', views.ds),
    url(r'^ba/', views.ba),
    url(r'^fa/', views.fa),
    url(r'^mvt/', views.mvt),
    url(r'^mft/', views.mft),
    url(r'^ps/', views.ps),
    url(r'^soc/', views.soc),
    url(r'^sync/', views.sync),
    url(r'^disk/',include('disk_sched.urls'),name='disk'),
    url(r'^process/',include('process.urls'))
]

ossim/process/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

app_name = 'process'
urlpatterns =[
    url(r'^$', views.home, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^demo/(?P<pk>[0-9]+)/$', views.demo, name='demo'),
    url(r'^gateway/$', views.gateway, name='gateway'),
]

ossim/process/models.py
from django.db import models

# Create your models here.

class ProcessSchedAlg(models.Model):

    name = models.CharField(max_length=200)
    description = models.TextField()
    demourl = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name


class Adv(models.Model):
    alg = models.ForeignKey(ProcessSchedAlg, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)


    def __str__(self):
        return self.text

ossim/process/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse

# Create your views here.
from . models import ProcessSchedAlg
from . utils import rr,sjf,srtf,fcfs,prepri,priority,multilevel

def home(request):
    algos = ProcessSchedAlg.objects.all()
    context = {'algos': algos}
    return render(request, 'process/index.html',context = context)

def detail(request,pk):
    alg = get_object_or_404(ProcessSchedAlg, pk=pk)
    context = {'alg':alg,
               }
    return render(request,'process/detail.html',context=context)

def demo(request,pk):
    if(pk=='1'):
        return render(request,'process/process.html')
    elif(pk=='2'):
        return render(request,'process/priority.html')
    elif(pk=='3'):
        return render(request,'process/multiLevel.html')

@csrf_exempt
def gateway(request):

    if request.method == 'POST':
        data = request.POST.get('value')
        data = json.loads(data)
        alg = request.POST.get('algo')
        alg=json.loads(alg)
        print(data)
        if(alg=="RR"):
        	tq = request.POST.get('tq')
        	tq = json.loads(tq)
        	result = rr(data,tq)
        elif(alg=="FCFS"):
            result = fcfs(data)
        elif(alg=="SRTF"):
            result = srtf(data)
        elif(alg=="SJF"):
            result = sjf(data)
        elif(alg=="PP"):
            result = prepri(data)
        elif(alg=="NPP"):
            result = priority(data)
        elif(alg=="MULTIQ"):
            tq = request.POST.get('tq')
            tq = json.loads(tq)
            table={'data':data,'tq':tq}
            queues,gantt,table = multilevel(table)
            result = {"queues":queues[:len(queues)-1], "gantt":gantt,"table":table}
        print(result)
    return JsonResponse(result)

ossim/process/templates/process/detail.html
{{ alg.name }}
{{ alg.description }}

{% for adv in alg.adv_set.all %}
{{adv.text}}
{% endfor %}

ossim/process/templates/process/index.html
<head>
    
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <style>
    h1{color:grey;}
    .lichoice{
        margin: 20px;
        width:300px;
         outline: 2px solid grey;
         box-shadow: 5px 5px grey;
         color: white;
    }
     .wikichoice{
        margin: 20px;
       width:300px;
         outline: 2px solid grey;
         box-shadow: 5px 5px grey;
         color: white;
    }
    body{
        background-image: url("http://blog.hostbaby.com/wp-content/uploads/2013/07/scuffedstatic_dark1400x900.jpg");
    }
</style>
</head>
{% block title %} <title> Process Scheduling </title> {% endblock %}


{% block links %}
{% load static %}
<link href="{%static 'filesystem/styles.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
 <nav role="navigation" class="navbar navbar-default">
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li class="active"><a href="/process/">Process Scheduling</a></li>
            <li><a href="/memory/page/">Page Replacement</a></li>
            <li><a href="/disk/">Disk Scheduling</a></li>
            <li><a href="/synchro/semaphores/">Semaphores</a></li>
            <li><a href="/synchro/socket/">Sockets</a></li>
            <li><a href="/filesystem/">File Structure</a></li>
            <li><a href="/mat/">Memory Allocation</a></li>
            <li><a href="/synchro/deadlocks/">Banker's Algorithm</a></li>
        </ul>
    </div>
</nav> -->

<center><div>
<h1 class="hed">Process Scheduling</h1>
<div id="choice">
    <ul id="ulchoice">
            <a href="/process/demo/1/"><li class="lichoice">SJF, FCFS, RR, SRTF Demo</li></a>
            <a href="/process/demo/2/"><li class="lichoice">Priority Scheduling</li></a>
            <a href="/process/demo/3/"><li class="lichoice">Multi Level Queue Scheduling</li></a>
            <!-- <a href="/wiki/process/"><li class="wikichoice">Wiki</li></a> -->
    </ul>
</div>
</div></center>
{% endblock %}

{% block style %}
<style>

</style>

{% endblock %}

ossim/process/templates/process/multiLevel.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <title>
    Process
  </title>
  <script type='text/javascript' src='{% static 'js/input1.js' %}'></script>
  <script type='text/javascript' src='{% static 'js/display13.js' %}'></script>
  <link rel="stylesheet" href='{% static 'css/demo1.css' %}'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<body style="background-image: url('https://i.pinimg.com/originals/9d/4d/07/9d4d07ca7d591bb3cd3d9f4df2624bbf.jpg">
  <div class="" style="opacity:0.8"><h1 style="text-align:center;text-align: center;text-shadow: 1px 1px blue">
    <b style="color:white">MultiLevel Queue Scheduling</b>
    </h1>
  </div>
  <div class="container" style="color:white">

    <div class="col-lg-6" style="">

        

        <div class="container">
          <div id="output">
          </div>
          <br>
          <div class="card" style="height:50px;">
              <div style="width:250px;float:left;text-align:left;color:white">
                Enter arrival time:
              <input style="width:200px;" id="newarrivaltime" class="form-control" type="number" min="0" value=""></input>
              </div>
              <div style="width:300px;float:left;text-align:left;color:white">
                Enter burst time:
                <input style="width:200px;float:left;" id="newbursttime" class="form-control" type="number" min="0" value=""></input>
              </div>
              <div style="width:300px;float:left;text-align:left;color:white">
                Enter Priority:
                        <br>
                            <select class="form-control" id="sel1" style="width:200px;color:white;background-color: #CD853F">
                              <option>Foreground Process(1)</option>
                              <option>Background Process(0)</option>
                            </select>
              </div>
              <button class="btn btn-success" onclick="addToList()" style="float:left;margin-top:20px;margin-left:10px;">Add</button>
          </div>

        </div>
        <br><br>

        <div class="" style="height:20px;">
            <button style="float:right;background-color:#99004D;color:white;" id="sender" class="btn btn-primary"><b>Send data</b></button>
        </div>
    </div>
    <div class="col-lg-6"></div>

  </div>
<hr>
    <!-- Queue Status -->
  <div class="container" style="background-color: white;opacity:0.9;margin-bottom: 20px">
    <div class="col-lg-6">
      <div class="" style="padding:0px;background-color: gray">
        <h3><b>Queue Status</b></h3>
      </div>
      <div class="" id="qstat" style="padding:10px;text-align:left;">
      </div>
    </div>
    <div class="col-lg-6">
      <div class="">
        <div class="" style="padding:0px;background-color: gray" >
          <h3><b>Table</b></h3>
        </div>
        <div class="panel-content">
          <table id="ptab" class="table table-bordered">
            <thead>
              <tr id="thead">
                <th>PNO.</th>
                <th>Priority</th>
                <th>Arrival time</th>
                <th>Burst time</th>
                <th>Completion time</th>
                <th>Waiting time</th>
                <th>Turn-around time</th>
              </tr>
              <tbody id="ptable">

              </tbody>
            </thead>
          </table>
        </div>
      </div>
    </div>
  </div>
<!-- Operations Taking Place -->
<!--   <div class="panel panel-warning" style="width:50%;float:left;">
    <div class="panel-heading">
      <h3>Operations Taking Place</h3>
    </div>
    <div id="comments" class="panel-content">
    </div>
  </div> -->
  <!-- Table -->

  <!--Gantt-->
  <hr>
  <div class="container" style="background-color: white;opacity:0.9;margin-bottom: 20px">
    <div class="panel">
      <div class="" style="padding:0px;background-color: gray">
        <h3>
        <b>Gantt chart</b>
        </h3>
      </div>
      <div id="gantth"></div>
      <br>
      <div id="outer-div">
      </div>
      <br>
    </div>
  </div>
</body>
</html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
//result queues , gantt,table
    function displayQueue(){
	// qstat = [{'FQ':[1,2,3,4,5],'BQ':[2,3]},{'FQ':[1,2],'BQ':[2,3]},{'FQ':[1,3],'BQ':[2]}]
	var i;
  var output = document.getElementById("qstat");
  output.setAttribute("style","height:"+100*qstat.length+"px;padding:10px;");
	for(i=0;i<qstat.length;++i){
    var card = document.createElement("div");
    card.insertAdjacentHTML( 'beforeend', "<h4>t = "+qstat[i].time+"</h4><hr style='border-top: 1px solid #3c763d;'>" );
    card.setAttribute("style","text-align:center");
    var lcard = document.createElement("div");
    lcard.setAttribute("id","lqstat"+i);
    lcard.setAttribute("style","float:left;width:50%;;height:20px");
    var rcard = document.createElement("div");
    rcard.setAttribute("id","rqstat"+i);
    rcard.setAttribute("style","float:right;width:50%;height:20px");
    lcard.insertAdjacentHTML( 'beforeend', "<div style='float:left;'>Foreground : </div>" );
		var j;
		for(j=0;j<qstat[i]['FQ'].length;++j){
      lcard.insertAdjacentHTML( 'beforeend', "<div style='height:20px;width:50px;text-align:center;float:left;border-style: dotted;'>" + qstat[i]['FQ'][j] + "</div>" );
			// $("#lqstat"+i).append("<div style='height:50px;width:50px;text-align:center;float:left;border-style: dotted;'>" + qstat[i]['FQ'][j] + "</div>");
		}
    rcard.insertAdjacentHTML( 'beforeend', "<div style='float:left;'>Background : </div>");
		// $("#rqstat"+i).append("<br><br><br><div style='float:left;'>Background : </div>");
		var j;
		for(j=0;j<qstat[i]['BQ'].length;++j){
      rcard.insertAdjacentHTML( 'beforeend', "<div style='height:20px;width:50px;text-align:center;float:left;border-style: dotted;'>" + qstat[i]['BQ'][j] + "</div>");
		}
    card.appendChild(lcard);
    card.appendChild(rcard);
    output.appendChild(card)
    console.log(output);
    card.insertAdjacentHTML( 'beforeend', "<hr style='border-top: 1px solid #3c763d;'>")
	}
    }
    $('#sender').click(function(){
    var text = JSON.stringify(stuff);
    var alg = JSON.stringify("MULTIQ");
    var mytq = JSON.stringify(2);
    //console.log(text);
    console.log({value:text, algo:alg})
    $.post('/process/gateway/',{value:text, algo:alg, tq:mytq}, function(result){
      console.log(result);
      sequence = result["gantt"];
      a = result["table"]
      qstat = result["queues"];
      avgwt =0;
      avgtat =0;
      for(i=0;i<a.length;++i){
        avgwt += a[i].wt;
        avgtat += a[i].tat;
      }
      total = sequence.length;
      var new_sequence = []
      if(sequence[0].start!=0) new_sequence.push({start:0,stop:sequence[0].start,no:-1,type:"IDLE"});
      new_sequence.push(sequence[0])
      for(i=1;i<total;i++){
        if(sequence[i].start!=sequence[i-1].stop)
          new_sequence.push({start:sequence[i-1].stop,stop:sequence[i].start,no:-1,type:"IDLE"});
        new_sequence.push(sequence[i]);
      }
      sequence = new_sequence;
      total = sequence.length;
      console.log(qstat);
      total = sequence.length;
      pixel = 0;
      i = 0;
      $('#outer-div,#comments,#ptable,#qstat,#gantth').empty();
      // $('#thead').append('<th>PNO.</th> <th>Arrival time</th>  <th>Burst time</th>  <th>Completion time</th>  <th>Waiting time</th>  <th>Turn-around time</th>');
      totalTime = sequence[total-1].stop;
      pixel = parseInt(800/totalTime);
      containerWidth = pixel*totalTime + 2;
      $('#outer-div').css('width',containerWidth+'px');
      displayBlock(i);
      displayQueue();
    });
    });
</script>

ossim/process/templates/process/multiLevel0.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <title>
    Process
  </title>
  <script type='text/javascript' src='{% static 'js/input1.js' %}'></script>
  <script type='text/javascript' src='{% static 'js/display13.js' %}'></script>
  <link rel="stylesheet" href='{% static 'css/demo1.css' %}'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<body style="padding:10px;">
  <div class="panel panel-danger">
      <div class="panel-heading"><h1 style="text-align:center;text-align: center;text-shadow: 1px 1px blue">
        MultiLevel Queue Scheduling
      </h1></div>
  <div class="panel-body">

    <div id="output">
    </div>

    <div class="card" style="height:70px;">
        <div style="width:250px;float:left;text-align:left;color:#800000">
          Enter arrival time:
          <input style="width:200px;"id="newarrivaltime" class="form-control" type="text" value=""></input>
        </div>
        <div style="width:300px;float:left;text-align:left;color:#800000">
          Enter burst time:
          <input style="width:200px;float:left;" id="newbursttime" class="form-control" type="text" value=""></input>
        </div>
        <div style="width:300px;float:left;text-align:left;color:#800000">
          Enter Priority:
                  <br>
                      <select class="form-control" id="sel1" style="width:200px;color:white;background-color: #CD853F">
                        <option>Foreground Process(1)</option>
                        <option>Background Process(0)</option>
                      </select>
                  </div>
          <button class="btn btn-success" onclick="addToList()" style="float:left;margin-top:20px;margin-left:10px; ">Add</button>
        </div>
    </div>
  </div>

    <div class="panel-footer" style="height:50px;">
      <button style="float:right;background-color:#99004D;color:white;" id="sender" class="btn btn-primary">Send the entire data</button>
    </div>
  </div>
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3>
      Gantt chart
    </h3>
    </div>
    <div id="gantth"></div>
    <br><br>
    <div id="outer-div">
  </div>
    <br><br>
</div>
  <div class="panel panel-success" style="width:50%;float:left;">
  <div class="panel-heading">
    <h3>Operations Taking Place</h3>
  </div>
  <div id="comments" class="panel-content">
  </div>
</div>
  <div class="panel panel-primary" style="width:50%;float:left;">
  <div class="panel-heading">
    <h3>Table</h3>
  </div>
    <div class="panel-content">
  <table id="ptab" class="table table-bordered" style=>
  <thead>
  <tr id="thead">
  <th>PNO.</th>
  <th>Arrival time</th>
  <th>Burst time</th>
  <th>Completion time</th>
  <th>Waiting time</th>
  <th>Turn-around time</th>
  </tr>
  <tbody id="ptable">

  </tbody>
  </thead>
  </table>
    </div>
    </div>
</body>
</html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
    $('#sender').click(function(){
    var text = JSON.stringify(stuff);
    var alg = JSON.stringify("MULTIQ");
    var mytq = JSON.stringify(2);
    //console.log(text);
    console.log({value:text, algo:alg})
    $.post('/process/gateway/',{value:text, algo:alg, tq:mytq}, function(result){
      sequence = result["gantt"];
      a = result["table"]
      avgwt =0;
      avgtat =0;
      for(i=0;i<a.length;++i){
        avgwt += a[i].wt;
        avgtat += a[i].tat;
      }
      total = sequence.length;
      pixel = 0;
      i = 0;
      $('#outer-div,#comments,#ptable,#gantth').empty();
      // $('#thead').append('<th>PNO.</th> <th>Arrival time</th>  <th>Burst time</th>  <th>Completion time</th>  <th>Waiting time</th>  <th>Turn-around time</th>');
      totalTime = sequence[total-1].stop;
      pixel = parseInt(800/totalTime);
      containerWidth = pixel*totalTime + 2;
      $('#outer-div').css('width',containerWidth+'px');
      displayBlock(i);
    });
    });
</script>

ossim/process/templates/process/priority.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <title>
    Process
  </title>
  <style type="text/css">
    body{
      background: https://www.solomonedwards.com/wp-content/uploads/2017/01/maxresdefault-1024x576.jpg;
    }
  </style>
  <script type='text/javascript' src='{% static 'js/inputpri.js' %}'></script>
  <script type='text/javascript' src='{% static 'js/displaypri4.js' %}'></script>
  <link rel="stylesheet" href='{% static 'css/demo1.css' %}'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<body  style="background-image: url('https://www.solomonedwards.com/wp-content/uploads/2017/01/maxresdefault-1024x576.jpg"  >
    <div class="" style="opacity:0.8"><h1 style="text-align:center;text-align: center;text-shadow: 1px 1px blue">
      <b style="color:white">Priority Process Scheduling</b>
      </h1>
    </div>
    <div class="container-fluid">
      <div class="col-lg-6">
        <div class="container">

          <div id="output" style="background-color:white">
          </div>
          <br>
          <div class="container-fluid" style="color:white">
              <div class="col-lg-2">
                <b >Enter arrival time:</b>
                <input style="width:150px;"id="newarrivaltime" class="form-control" type="text" value=""></input>
              </div>
              <div  class="col-lg-2">
                <b>Enter burst time:</b>
                <input style="width:150px;" id="newbursttime" class="form-control" type="text" value=""></input>
              </div>
              <div  class="col-lg-2">
                <b>Enter Priority:</b>
                <br>
                <input style="width:150px;" id="newPriority" class="form-control" type="text" value=""></input>
                
              </div>
              <div  class="col-lg-3" style="color:white;bottom:10px;padding-top: 5px">
                <label for="sel1" style="">Select Algorithm to be used :</label>
                  <br>
                <select class="form-control" id="sel1" style="width:200px;background-color: grey;color:white">
                  <option>Preemptive Priority(PP)</option>
                  <option>Non-preemptive Priority(NPP)</option>
                </select>
              </div>
              <div class="col-lg-1" style="padding-top:15px">
                <button class="btn btn-danger" onclick="addToList()" style="float:left;margin-left:10px;color:white;">Add</button>
              </div>
          </div>


        </div>

        <div class="" style="height:50px;padding: 10px">
        	<button style="float: right;background-color: #33CC00;color: white" id="sender" class="btn btn-primary">Send the entire data</button>
        </div>
      </div>
      <div class="col-lg-6"></div>
    </div>

    <div class="container" style="width:50%;float:left;"">
      <div class="" style="background-color: white;opacity:0.8;margin-bottom: 20px;padding: 5px">
      	<h3><b>Operations Taking Place</b></h3>
      </div>
      <div id="comments" class="" style="background-color: white;opacity:0.8;margin-bottom: 20px;padding: 5px">
      </div>
    </div>
    <div class="container" style="width:50%;float:right; ">
      <div class=""  style="background-color: white;opacity:0.9;margin-bottom: 20px;padding: 5px">
      	<h3><b>Table</b></h3>
      </div>
      <div class="" style="background-color: white;opacity:0.9;margin-bottom: 20px;padding: 5px">
        <table id="ptab" class="table table-bordered">
          <thead>
       	    <tr id="thead">
             	<th>PNO.</th>
              <th>Priority</th>
            	<th>Arrival time</th>
            	<th>Burst time</th>
            	<th>Completion time</th>
            	<th>Waiting time</th>
            	<th>Turn-around time</th>
            </tr>
            <tbody id="ptable">

            </tbody>
          </thead>
        </table>
      </div>
    </div>
    <hr>
    <br><br>

    <div class="container" style="background-color: white;opacity:0.8;margin: 300px 0px 0px 100px;">
        <div class="" style="">
          <h3>
            <b>Gantt chart</b>
          </h3>
        </div>
        <div id="gantth"></div>
        <br>
        <div id="outer-div">
        </div>
        <br>
    </div>
</body>
</html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
    $('#sender').click(function(){
    var text = JSON.stringify(stuff);
    var alg = JSON.stringify($("#sel1").val().split("(")[1].split(")")[0])
    //console.log(text);
    $.post('/process/gateway/',{value:text, algo:alg}, function(result){
      sequence = result["gantt"];
      a = result["table"]
      avgwt =0;
      avgtat =0;
      for(i=0;i<a.length;++i){
        avgwt += a[i].wt;
        avgtat += a[i].tat;
      }
      total = sequence.length;
      pixel = 0;
      i = 0;
      $('#outer-div,#comments,#ptable,#gantth').empty();
      // $('#thead').append('<th>PNO.</th> <th>Arrival time</th>  <th>Burst time</th>  <th>Completion time</th>  <th>Waiting time</th>  <th>Turn-around time</th>');
      totalTime = sequence[total-1].stop;
      pixel = parseInt(800/totalTime);
      containerWidth = pixel*totalTime + 2;
      $('#outer-div').css('width',containerWidth+'px');
      displayBlock(i);
    });
    });
</script>